"""added personal email address column

Revision ID: 06e8a9805c77
Revises: 3853865e97ca
Create Date: 2024-08-28 15:43:36.544454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e8a9805c77'
down_revision: Union[str, None] = '3853865e97ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner', sa.Column('personal_email_address', sa.String(), nullable=True))
    op.create_unique_constraint('unique_email', 'learner', ['personal_email_address'])
    op.execute("UPDATE learner SET personal_email_address= CONCAT(LOWER(first_name), LOWER(surname), '@gmail.com')")
    op.alter_column('learner', 'personal_email_address', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_email', 'learner', type_='unique')
    op.drop_column('learner', 'personal_email_address')
    # ### end Alembic commands ###
