"""rename chatname column to rocketchat_user

Revision ID: 32a79309ae37
Revises: d5a7c6f6dd4d
Create Date: 2024-08-28 16:49:25.117577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a79309ae37'
down_revision: Union[str, None] = 'd5a7c6f6dd4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [column['name'] for column in  inspector.get_columns('learner')]
    if 'chatname' in columns:
        op.alter_column('learner', 'chatname', new_column_name='rocketchat_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learner', 'rocketchat_user', new_column_name='chatname')
    # ### end Alembic commands ###
