"""delete id_number column

Revision ID: 75f20e19b504
Revises: 32a79309ae37
Create Date: 2024-08-30 08:21:04.483548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f20e19b504'
down_revision: Union[str, None] = '32a79309ae37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [column['name'] for column in  inspector.get_columns('learner')]
    if 'id_number' in columns:
        op.drop_column('learner', 'id_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner', sa.Column('id_number', sa.String(), nullable=True))
    # ### end Alembic commands ###
