"""addedd cohort column

Revision ID: d743d2fd30ba
Revises: 06e8a9805c77
Create Date: 2024-08-28 16:22:42.889591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd743d2fd30ba'
down_revision: Union[str, None] = '06e8a9805c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [column['name'] for column in  inspector.get_columns('learner')]
    if 'cohort' not in columns:
        op.add_column('learner', sa.Column('cohort', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
        op.execute("UPDATE learner SET cohort='C25 Data Eng'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learner', 'cohort')
    # ### end Alembic commands ###
